baseURL = 'http://schneeboat.github.io/'
languageCode = 'en-us'
title = 'Snow'
theme = 'PaperMod'

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Alexia"
description = "Alexia's website'"
author = "Alexia"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"



  [params.label]
  text = "Home"
  

  [params.homeInfoParams]
  Title = "Hi there 💖"
  Content = '''
  Welcome to my website 
  
  I am still drafting...

  Will go live soon
  
  '''

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/snowboat/"

 
  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/schneeboat"



[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

